[package]
name = "pebble"
version = "0.6.2"
authors = ["Lukáš Hozda <luk.hozda@gmail.com>"]
license = "Fair"

[dependencies]
serde = "*"
serde_derive = "*"
toml = "*"
recipe-reader = "*"
ansi_term = "*"
